const data = {
  products: [
    {
      name: 'Nike Red shirt',
      slug: 'nike-red-shirt',
      category: 'Shirts',
      image: '/images/p1.png',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Nike Blue shirt',
      slug: 'nike-blue-shirt',
      category: 'Shirts',
      image: '/images/p2.png',
      price: 90,
      countInStock: 10,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 9,
      description: 'high quality shirt',
    },
    {
      name: 'Puma White shirt',
      slug: 'puma-blue-shirt',
      category: 'Shirts',
      image: '/images/p3.png',
      price: 110,
      countInStock: 9,
      brand: 'Puma',
      rating: 5.0,
      numReviews: 8,
      description: 'high quality shirt',
    },
    {
      name: 'Puma Red shirt',
      slug: 'puma-red-shirt',
      category: 'Shirts',
      image: '/images/p4.png',
      price: 110,
      countInStock: 9,
      brand: 'Puma',
      rating: 5.0,
      numReviews: 8,
      description: 'high quality shirt',
    },
    {
      name: 'Addidas stripe shirt',
      slug: 'addidas-stripe-shirt',
      category: 'Shirts',
      image: '/images/p5.png',
      price: 110,
      countInStock: 9,
      brand: 'addidas',
      rating: 3.5,
      numReviews: 8,
      description: 'high quality shirt',
    },
    {
      name: 'Addidas blue shirt',
      slug: 'addidas-blue-shirt',
      category: 'Shirts',
      image: '/images/p6.png',
      price: 110,
      countInStock: 9,
      brand: 'addidas',
      rating: 3.5,
      numReviews: 8,
      description: 'high quality shirt',
    },
  ],
}
export default data
